table 'Annual Average Inflation By State'
	lineageTag: 97e0bdd6-b911-492c-9a76-d7f470e42ce7

	measure 'Average Inflation' = AVERAGE('Annual Average Inflation By State'[Annual Average Inflation])
		lineageTag: cb823277-716d-487c-b9c9-6e47a039ad11

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column State
		lineageTag: 6d9dcf79-ccbe-4895-9dcf-ce886863a81e
		summarizeBy: none
		isNameInferred
		sourceColumn: Monthly Inflation Rate By State[State]

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9e1af862-dbb7-4d4c-a23c-b0acdc946768
		summarizeBy: none
		isNameInferred
		sourceColumn: Monthly Inflation Rate By State[Year]

		annotation SummarizationSetBy = User

	column 'Annual Average Inflation'
		lineageTag: 6746148f-d725-4f94-b238-e672376e9015
		summarizeBy: none
		isNameInferred
		sourceColumn: [Annual Average Inflation]

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Key = 'Annual Average Inflation By State'[State] & "-" & [Year]
		isHidden
		lineageTag: 2fb50aaa-e43a-4cd9-8acb-2ec2e1799590
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Annual Average Inflation By State' = calculated
		mode: import
		source = ```
				
				SUMMARIZE (
				    'Monthly Inflation Rate By State',
				    'Monthly Inflation Rate By State'[State],
				    'Monthly Inflation Rate By State'[Year],
				    "Annual Average Inflation",
				        AVERAGE ( 'Monthly Inflation Rate By State'[Inflation YoY] )
				)
				
				```

	annotation PBI_Id = 549867af5332442b8aa1c4134fa55e4f

