table 'Annual CPI Index By Category'
	lineageTag: 991ebae1-8641-449d-aa61-da070a2cf675

	measure 'Selected Category CPI Index' = ```
			
			SELECTEDVALUE ( 'Annual CPI Index By Category'[Index] )
			
			```
		lineageTag: 69d59dfd-14ab-4e34-95d7-6dafc220dd69

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1de8afce-b7fd-4f9e-9644-c5d352bc6426
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 39865b72-e133-4127-9f53-4f2680abfa13
			defaultHierarchy: LocalDateTable_1ae12617-2f0a-4873-aaa1-db18bb4e49b5.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Division
		dataType: string
		lineageTag: 4f8895f9-7050-4e2c-b7d6-3dfac77e14ce
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: double
		lineageTag: 459cdd54-9ee2-4684-8fa4-de0ae67f1eba
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Year = YEAR('Annual CPI Index By Category'[Date])
		formatString: 0
		lineageTag: 78fee4f1-b026-40c4-a943-82a555d11483
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Annual CPI Index By Category' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Desktop\MDITxDOSM\dataset\cpi_2d_annual.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}, {"division", type text}, {"index", type number}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([division] <> "overall")),
				    #"Renamed Columns" = Table.RenameColumns(#"Filtered Rows",{{"date", "Date"}, {"division", "Division"}, {"index", "Index"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

