table 'Annual Household Income'
	lineageTag: 8ac65470-d433-4574-8e90-6b7a38c6481e

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 901817b2-de07-4832-bb1a-1687430cc0d1
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 93aa14df-9dd0-4fdd-8e1d-97a508fc5f16
			defaultHierarchy: LocalDateTable_61888aa1-4d3f-4c76-811f-ec498813e935.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Mean Income (RM)'
		dataType: int64
		formatString: 0
		lineageTag: af0f864f-0b4b-4ec9-aeda-ba7280427c8b
		summarizeBy: none
		sourceColumn: Mean Income (RM)

		annotation SummarizationSetBy = User

	column 'Median Income (RM)'
		dataType: int64
		formatString: 0
		lineageTag: 96b3b58f-c1ef-4657-9cef-7a2f81303843
		summarizeBy: none
		sourceColumn: Median Income (RM)

		annotation SummarizationSetBy = User

	partition 'Annual Household Income' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Desktop\Datathon\hh_income.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"date", type date}, {"income_mean", Int64.Type}, {"income_median", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"date", "Date"}, {"income_mean", "Mean Income (RM)"}, {"income_median", "Median Income (RM)"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

