table 'Economic Indicator Index'
	lineageTag: af9a0689-764a-41a8-85d3-5c73f04e02dd

	column inflation
		dataType: double
		lineageTag: 47462a23-6a0f-4c46-af4d-1c3b72c23fd7
		summarizeBy: sum
		sourceColumn: inflation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ppi
		dataType: double
		lineageTag: e9305394-6376-4670-8117-2fdaac6c18ec
		summarizeBy: sum
		sourceColumn: ppi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cpi
		dataType: double
		lineageTag: d3b2c9ac-c579-4d42-adb7-f956008f2861
		summarizeBy: sum
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf
		dataType: double
		lineageTag: 8a93f40c-585a-4467-a3ab-e0acb90f0d5e
		summarizeBy: sum
		sourceColumn: lf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column employment_rate
		dataType: double
		lineageTag: c019e784-0e50-47f3-83f1-31231cf6b67a
		summarizeBy: sum
		sourceColumn: employment_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unemployment_rate
		dataType: double
		lineageTag: 2749e2b4-9f65-4b7b-98f2-8b988481ec63
		summarizeBy: sum
		sourceColumn: unemployment_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf_unemployed
		dataType: double
		lineageTag: d38c6892-acb1-42bc-8e57-204a927d13eb
		summarizeBy: sum
		sourceColumn: lf_unemployed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf_outside
		dataType: double
		lineageTag: 8cfe7b97-91fd-4b90-bb9e-93a223018c40
		summarizeBy: sum
		sourceColumn: lf_outside

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ep_ratio
		dataType: double
		lineageTag: 2ee16a7d-4958-4b07-bc59-e01bc4ef63ed
		summarizeBy: sum
		sourceColumn: ep_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag1
		dataType: double
		lineageTag: 61f4e10d-2ebb-48e6-a662-148d011a35da
		summarizeBy: sum
		sourceColumn: inflation_lag1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag2
		dataType: double
		lineageTag: ba723951-6519-4877-bf62-0ff4e3102201
		summarizeBy: sum
		sourceColumn: inflation_lag2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag3
		dataType: double
		lineageTag: 9c3835b3-81e3-4505-b487-1698b98225c5
		summarizeBy: sum
		sourceColumn: inflation_lag3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag4
		dataType: double
		lineageTag: de8f45b9-de35-423d-9da9-34d08922371f
		summarizeBy: sum
		sourceColumn: inflation_lag4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag5
		dataType: double
		lineageTag: d28352f7-e38b-4054-8125-edd2784d91dd
		summarizeBy: sum
		sourceColumn: inflation_lag5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag6
		dataType: double
		lineageTag: 24569f3a-db39-43bb-8863-7b8d5f793c0e
		summarizeBy: sum
		sourceColumn: inflation_lag6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column time_index
		dataType: int64
		formatString: 0
		lineageTag: 4e09dbdc-ccea-454b-9a4c-fd7dcea724bf
		summarizeBy: sum
		sourceColumn: time_index

		annotation SummarizationSetBy = Automatic

	column ppi_ma3
		dataType: double
		lineageTag: 9bc6891c-8708-41bd-9e2c-2df94de1dfbf
		summarizeBy: sum
		sourceColumn: ppi_ma3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_rate_ma3
		dataType: double
		lineageTag: c8f2810e-084b-4791-9b48-84e961f3056c
		summarizeBy: sum
		sourceColumn: u_rate_ma3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column economic_indicator_index
		dataType: double
		lineageTag: bd06a2dc-7f5d-42b4-bd77-67c959feff4c
		summarizeBy: sum
		sourceColumn: economic_indicator_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column economic_indicator_index_norm
		dataType: double
		lineageTag: 07c6eead-1caf-420d-91d8-67e091c254fb
		summarizeBy: sum
		sourceColumn: economic_indicator_index_norm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date = DATE(2010, 1, 1)
		formatString: General Date
		lineageTag: ab76d209-6315-4675-8bf5-6bcdac06b389
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 5229cf7f-f858-4294-a101-17f9b7867f4f
			defaultHierarchy: LocalDateTable_618f2da9-f8c8-4b0c-8587-287fece73b90.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Economic Indicator Index' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Desktop\MDITxDOSM\dataset\economic_indicator.csv"),[Delimiter=",", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"Unnamed: 0", Int64.Type}, {"inflation", type number}, {"ppi", type number}, {"cpi", type number}, {"lf", type number}, {"p_rate", type number}, {"u_rate", type number}, {"lf_unemployed", type number}, {"lf_outside", type number}, {"ep_ratio", type number}, {"inflation_lag1", type number}, {"inflation_lag2", type number}, {"inflation_lag3", type number}, {"inflation_lag4", type number}, {"inflation_lag5", type number}, {"inflation_lag6", type number}, {"time_index", Int64.Type}, {"ppi_ma3", type number}, {"u_rate_ma3", type number}, {"economic_indicator_index", type number}, {"economic_indicator_index_norm", type number}, {"is_forecasted", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"is_forecasted", "", "Unnamed: 0"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"p_rate", "employment_rate"}, {"u_rate", "unemployment_rate"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

