table 'Economic Indicator'
	lineageTag: 8f84cfab-6b09-4312-aab4-394363cac023

	column inflation
		dataType: double
		lineageTag: 179ffee8-d754-47a2-8c17-406f5a970c81
		summarizeBy: sum
		sourceColumn: inflation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ppi
		dataType: double
		lineageTag: 21ac45b7-aa87-4295-83fa-9a54578c18e9
		summarizeBy: sum
		sourceColumn: ppi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cpi
		dataType: double
		lineageTag: be5bd529-9346-45b1-9dd5-57da27b2c7bf
		summarizeBy: sum
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf
		dataType: double
		lineageTag: 04a385b8-bf35-4e54-a2f3-20a869e5adbd
		summarizeBy: sum
		sourceColumn: lf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column p_rate
		dataType: double
		lineageTag: c6b54f18-7251-4c9d-bbfd-16228dd22a2a
		summarizeBy: sum
		sourceColumn: p_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_rate
		dataType: double
		lineageTag: aa9eb094-e74d-463a-8b3c-1b73b855d034
		summarizeBy: sum
		sourceColumn: u_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf_unemployed
		dataType: double
		lineageTag: fac1b87b-6bc9-4a50-b99c-c0b3b799b0b4
		summarizeBy: sum
		sourceColumn: lf_unemployed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf_outside
		dataType: double
		lineageTag: 94458244-4fe7-40ee-8ffa-094d87548625
		summarizeBy: sum
		sourceColumn: lf_outside

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ep_ratio
		dataType: double
		lineageTag: 0f4896e8-e7b0-45b1-8e81-cf8c0d3cfcf4
		summarizeBy: sum
		sourceColumn: ep_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Economic Indicator' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Desktop\MDITxDOSM\dataset\economic_indicator_table.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"date", type date}, {"inflation", type number}, {"ppi", type number}, {"cpi", type number}, {"lf", type number}, {"p_rate", type number}, {"u_rate", type number}, {"lf_unemployed", type number}, {"lf_outside", type number}, {"ep_ratio", type number}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"date", ""}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"inflation", type number}, {"ppi", type number}, {"cpi", type number}, {"lf", type number}, {"p_rate", type number}, {"u_rate", type number}, {"lf_unemployed", type number}, {"lf_outside", type number}, {"ep_ratio", type number}})
				in
				    #"Changed Type1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

