table 'Economic Indicator'
	lineageTag: ee132f17-c12d-4094-839f-48db40001f70

	measure 'Index Deviation' =
			
			VAR LatestValue =
			    -- Get the value for the most recent date in the data
			    LASTNONBLANKVALUE(
			        'Economic Indicator'[Date],
			        SUM('Economic Indicator'[economic_indicator_index_norm])
			    )
			VAR Baseline = 100
			RETURN
			    -- Calculate the absolute distance from the baseline
			    IF(NOT ISBLANK(LatestValue), ABS(LatestValue - Baseline), 0)
		lineageTag: dd6a82c3-510c-4f15-857b-27a1ad955575

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Selected Feature Value' = ```
			
			VAR SelectedFeature = SELECTEDVALUE('Pca Loading'[feature])
			RETURN
			SWITCH(
			    SelectedFeature,
			    "inflation", AVERAGE('Economic Indicator'[inflation]),
			    "ppi", AVERAGE('Economic Indicator'[ppi]),
			    "lf", AVERAGE('Economic Indicator'[lf]),
			    "p_rate", AVERAGE('Economic Indicator'[p_rate]),
			    "u_rate", AVERAGE('Economic Indicator'[u_rate]),
			    "lf_unemployed", AVERAGE('Economic Indicator'[lf_unemployed]),
			    "lf_outside", AVERAGE('Economic Indicator'[lf_outside]),
			    "cpi", AVERAGE('Economic Indicator'[cpi]),
			    BLANK()
			)
			
			```
		lineageTag: 09b27303-5e4e-417d-b873-4fdd4ae3b4a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation
		dataType: double
		lineageTag: c7cb18ec-c5f0-4fb6-8588-fd3f1e582744
		summarizeBy: sum
		sourceColumn: inflation

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ppi
		dataType: double
		lineageTag: 59dc0113-5aef-4f6a-8733-6ce0eaf043cd
		summarizeBy: sum
		sourceColumn: ppi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column cpi
		dataType: double
		lineageTag: dde1549b-3024-47cd-b6f5-a2df215503c8
		summarizeBy: sum
		sourceColumn: cpi

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf
		dataType: double
		lineageTag: 33ef6698-0891-42f1-8f8f-9836622122f5
		summarizeBy: none
		sourceColumn: lf

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column p_rate
		dataType: double
		lineageTag: 75851845-3cb8-4f1f-822b-043da02fc4cc
		summarizeBy: sum
		sourceColumn: p_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_rate
		dataType: double
		lineageTag: c7521483-b287-441b-88cb-a0838d01de4c
		summarizeBy: sum
		sourceColumn: u_rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf_unemployed
		dataType: double
		lineageTag: 2a8a866c-e344-488b-b179-f900550465ad
		summarizeBy: sum
		sourceColumn: lf_unemployed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column lf_outside
		dataType: double
		lineageTag: 60544a8a-b21f-45ed-b172-2b61b180d97e
		summarizeBy: sum
		sourceColumn: lf_outside

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ep_ratio
		dataType: double
		lineageTag: aa443856-5058-4410-b222-f6e93300f4e7
		summarizeBy: sum
		sourceColumn: ep_ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag1
		dataType: double
		lineageTag: 16cbb182-15d6-4138-b73f-1ccf3632c598
		summarizeBy: sum
		sourceColumn: inflation_lag1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag2
		dataType: double
		lineageTag: ea8acb80-3104-4ac2-a3bd-9c0adfb33c71
		summarizeBy: sum
		sourceColumn: inflation_lag2

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag3
		dataType: double
		lineageTag: cd57cc19-185b-429c-81ab-0983a66e9c4b
		summarizeBy: sum
		sourceColumn: inflation_lag3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag4
		dataType: double
		lineageTag: f8b525f0-5bc1-4f32-9546-e6263055e001
		summarizeBy: sum
		sourceColumn: inflation_lag4

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag5
		dataType: double
		lineageTag: 027d7fa7-fa77-491f-af9a-ad8a9bebae63
		summarizeBy: sum
		sourceColumn: inflation_lag5

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column inflation_lag6
		dataType: double
		lineageTag: 6e1e2829-199b-4de5-a325-bc75c5717dc1
		summarizeBy: sum
		sourceColumn: inflation_lag6

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column time_index
		dataType: double
		lineageTag: a321203f-d9b9-42e6-9ea5-abf4349452fa
		summarizeBy: sum
		sourceColumn: time_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ppi_ma3
		dataType: double
		lineageTag: e776d7c3-b6f8-480d-9d64-a1c51eb62386
		summarizeBy: sum
		sourceColumn: ppi_ma3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column u_rate_ma3
		dataType: double
		lineageTag: 3333915d-cca6-41c7-b2cc-bf68e9236b65
		summarizeBy: sum
		sourceColumn: u_rate_ma3

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column economic_indicator_index
		dataType: double
		lineageTag: 7c187a09-f679-4cb2-94df-e3ad965cf44d
		summarizeBy: sum
		sourceColumn: economic_indicator_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column economic_indicator_index_norm
		dataType: double
		lineageTag: 967beb3c-571e-4221-96b3-c53a53f4cc38
		summarizeBy: sum
		sourceColumn: economic_indicator_index_norm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date =
			
			VAR StartDate = DATE(2010, 1, 1) -- Change to your actual first month
			RETURN
			EDATE(StartDate, [time_index])
		formatString: General Date
		lineageTag: 8fe24b44-01e9-442a-9065-59f3c3a13904
		summarizeBy: none

		variation Variation
			isDefault
			relationship: 79a931e8-7d78-417e-bd19-1cdcb9b13aba
			defaultHierarchy: LocalDateTable_7fb86b8f-9432-47ad-b85d-aae6d88b050b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	partition 'Economic Indicator' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Desktop\MDITxDOSM\dataset\economic_indicator_new.csv"),[Delimiter=",", Columns=23, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"", Int64.Type}, {"Unnamed: 0", Int64.Type}, {"inflation", type number}, {"ppi", type number}, {"cpi", type number}, {"lf", type number}, {"p_rate", type number}, {"u_rate", type number}, {"lf_unemployed", type number}, {"lf_outside", type number}, {"ep_ratio", type number}, {"inflation_lag1", type number}, {"inflation_lag2", type number}, {"inflation_lag3", type number}, {"inflation_lag4", type number}, {"inflation_lag5", type number}, {"inflation_lag6", type number}, {"time_index", Int64.Type}, {"ppi_ma3", type number}, {"u_rate_ma3", type number}, {"economic_indicator_index", type number}, {"economic_indicator_index_norm", type number}, {"is_forecasted", Int64.Type}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"", "Unnamed: 0"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"inflation", type number}, {"ppi", type number}, {"cpi", type number}, {"lf", type number}, {"p_rate", type number}, {"u_rate", type number}, {"lf_unemployed", type number}, {"lf_outside", type number}, {"ep_ratio", type number}, {"inflation_lag1", type number}, {"inflation_lag2", type number}, {"inflation_lag3", type number}, {"inflation_lag4", type number}, {"inflation_lag5", type number}, {"inflation_lag6", type number}, {"time_index", type number}, {"ppi_ma3", type number}, {"u_rate_ma3", type number}, {"economic_indicator_index", type number}, {"economic_indicator_index_norm", type number}, {"is_forecasted", type number}}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type1",{"is_forecasted"})
				in
				    #"Removed Columns1"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

