table mcoicop
	lineageTag: 4106b5bb-c819-47ab-8aff-b39d761cd7f4

	column Division
		dataType: string
		lineageTag: c7491aad-619e-457b-90fe-7e842cfd70ce
		summarizeBy: none
		sourceColumn: Division

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: dbfacb2f-4eda-445a-8cca-fa21c60ac7a1
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition mcoicop = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\User\Desktop\MDITxDOSM\dataset\mcoicop.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"digits", Int64.Type}, {"division", type text}, {"group", type text}, {"class", type text}, {"subclass", type text}, {"desc_en", type text}, {"desc_bm", type text}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each ([group] = "-")),
				    #"Removed Columns" = Table.RemoveColumns(#"Filtered Rows",{"digits", "group", "class", "subclass", "desc_bm"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns",{{"desc_en", "Category"}, {"division", "Division"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

