table 'Mean Income Female'
	lineageTag: fe0f5746-13a4-4384-aaa1-e40393f913e9

	column Year
		dataType: string
		lineageTag: 69ca489b-0e10-46db-ad05-37d5c945564b
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Mean Income (RM)'
		dataType: double
		lineageTag: 5ac19e8a-b8da-4fb9-9ab9-ce8d0e7e8b4a
		summarizeBy: sum
		sourceColumn: Mean Income (RM)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Gender
		dataType: string
		lineageTag: 8ef4b805-9d90-47b2-9f86-b5c3399c1337
		summarizeBy: none
		sourceColumn: Gender

		annotation SummarizationSetBy = Automatic

	partition 'Mean Income Female' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\User\Desktop\Datathon\JADUAL PENERBITAN SURVEI GAJI & UPAH 2023.xlsx"), null, true),
				    #"JADUAL A2 Umur Perempuan_Sheet" = Source{[Item="JADUAL A2 Umur Perempuan",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"JADUAL A2 Umur Perempuan_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"A2: Bilangan penerima, Penengah dan purata gaji & upah bulanan pekerja mengikut kumpulan umur dan jantina, Malaysia, 2010–2023 (samb.)", type text}, {"Column2", type number}, {"Column3", type number}, {"Column4", type number}, {"Column5", type number}, {"Column6", type number}, {"Column7", type number}, {"Column8", type number}, {"Column9", type number}, {"Column10", type number}, {"Column11", type number}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type number}, {"Column16", type text}, {"Column17", type any}, {"Column18", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"A2: Bilangan penerima, Penengah dan purata gaji & upah bulanan pekerja mengikut kumpulan umur dan jantina, Malaysia, 2010–2023 (samb.)", "Column17", "Column18"}),
				    #"Removed Top Rows" = Table.Skip(#"Removed Columns",2),
				    #"Removed Top Rows1" = Table.Skip(#"Removed Top Rows",1),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows1", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers1",{{"2010", type number}, {"2011", type number}, {"2012", type number}, {"2013", type number}, {"2014", type number}, {"2015", type number}, {"2016", type number}, {"2017", type number}, {"2018", type number}, {"2019", type number}, {"2020r", type number}, {"2021r", type number}, {"2022r", type number}, {"2023", type number}, {"Age group", type text}}),
				    #"Removed Bottom Rows" = Table.RemoveLastN(#"Changed Type1",13),
				    #"Removed Top Rows2" = Table.Skip(#"Removed Bottom Rows",22),
				    #"Unpivoted Other Columns" = Table.UnpivotOtherColumns(#"Removed Top Rows2", {"Age group"}, "Attribute", "Value"),
				    #"Removed Columns1" = Table.RemoveColumns(#"Unpivoted Other Columns",{"Age group"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Columns1",{{"Attribute", "Year"}, {"Value", "Mean Income (RM)"}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Renamed Columns","2020r","2020",Replacer.ReplaceText,{"Year"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","2021r","2021",Replacer.ReplaceText,{"Year"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","2022r","2022",Replacer.ReplaceText,{"Year"}),
				    #"Added Custom" = Table.AddColumn(#"Replaced Value2", "Gender", each "Female")
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

